import "./styles/globals.css";
import type { Metadata } from "next";

import { inter } from "./fonts";

export const metadata: Metadata = {
  title: "Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en" className={inter.className}>
      <body>{children}</body>
    </html>
  );
}
